export const DEFAULT_BRAND_NAME = "Acme";

export const APP_DESKTOP_TOP_NAV_HEIGHT = 64;
export const APP_DESKTOP_LEFT_NAV_WIDTH = 192;
export const APP_DESKTOP_RIGHT_NAV_WIDTH = 296;

export const FLOW_EDITOR_COLUMN_WIDTH = 272;
